### ISSUE TITLE
install doesnt seem to work

### ISSUE THREAD

**Issue by trulytrojan** [redislabsdemo/RedisTimeSeries-Grafana#2]
➜  RedisTimeSeries-Grafana git:(master) npm install package.json
npm WARN deprecated package.json@2.0.1: Use pkg.json instead.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.13.0","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
npm WARN RedisTimeSeries-Grafana-datasource@0.0.1 No repository field.

+ package.json@2.0.1
added 74 packages from 36 contributors and audited 162 packages in 4.891s
found 0 vulnerabilities

==================================================

➜  RedisTimeSeries-Grafana git:(master) node --version
v12.13.0
==================================================
➜  RedisTimeSeries-Grafana git:(master) node index.js
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'express'
Require stack:
- /Users/workerbee/Documents/fun/code/RedisTimeSeries-Grafana/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/workerbee/Documents/fun/code/RedisTimeSeries-Grafana/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/workerbee/Documents/fun/code/RedisTimeSeries-Grafana/index.js'
  ]
}

**Comment by iamshreeram** [comment]
@trulytrojan , Can you try any of below 
1. `npm install` (or) `npm install --save express body-parser redis` // this will install all necessary modules
2. `node index.js 6379` // 6380 doesnt work. default port is 6379
